name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  security:
    uses: rundeck-plugins/.github/.github/workflows/snyk-scan-reusable.yml@main
    with:
      # Optional: Java version for build environment (default: '11')
      # Supported versions: 8, 11, 17, 21
      java-version: '11'
      
      # Optional: Java distribution (default: 'temurin')
      # Options: temurin, zulu, adopt, corretto, microsoft, etc.
      java-distribution: 'temurin'
      
      # Optional: Snyk detection depth (default: '10')
      # Higher values scan deeper but take longer
      snyk-detection-depth: '10'
      
      # Optional: GitHub runner type (default: 'ubuntu-latest')
      # Options: ubuntu-latest, ubuntu-20.04, windows-latest, macos-latest
      runs-on: 'ubuntu-latest'
    secrets:
      # Organization secrets - automatically available to all repos
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}