name: Security Scan (Reusable)

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: false
        default: '11'
        type: string
      java-distribution:
        description: 'Java distribution to use'
        required: false
        default: 'temurin'
        type: string
      snyk-detection-depth:
        description: 'Snyk detection depth'
        required: false
        default: '10'
        type: string
      runs-on:
        description: 'Runner to use'
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      SNYK_TOKEN:
        description: 'Snyk authentication token'
        required: true
      SNYK_ORG_ID:
        description: 'Snyk organization ID'
        required: true

jobs:
  snyk_security:
    name: Snyk Security Scan
    runs-on: ${{ inputs.runs-on }}
    
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          
      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/cli/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/
      
      - name: Verify Snyk installation
        run: snyk --version

      - name: Snyk Clear Config (logout)
        run: snyk config clear
          
      - name: Configure Snyk organization
        run: snyk config set org='${{ env.SNYK_ORG_ID }}'

      - name: Confirm Snyk Identity
        run: snyk whoami --experimental
          
      - name: Run Snyk monitor (main/master branch only)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: snyk monitor --all-projects --detection-depth=${{ inputs.snyk-detection-depth }}
          
      - name: Skip monitor for feature branches
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
        run: echo "Skipping monitor for feature branch (${{ github.ref }}) - no data sent to dashboard"
        
      - name: Test for vulnerabilities
        run: snyk test --all-projects --detection-depth=${{ inputs.snyk-detection-depth }} || true